---

name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  unit-tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Run tests
        run: yarn test

  code-quality:
    name: Linting
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: ./.github/actions/setup-node

      - name: Lint
        run: yarn lint

      - name: Typecheck
        run: yarn typecheck
