name: main

on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci:
    name: "Continuous Integration"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    steps:
      - name: "Clone Repository"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.0
      - name: "Setup Node"
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: "Install"
        run: pnpm install --ignore-scripts
      - name: "Commitlint"
        run: pnpm commitlint
      - name: "Format"
        run: pnpm format
      - name: "Lint"
        run: pnpm lint
      - name: "Typecheck"
        run: pnpm typecheck
      - name: "Test"
        run: pnpm test
